plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.instrumentsandnav'
    compileSdk 36

    defaultConfig {
        applicationId 'com.example.instrumentsandnav'
        minSdk 26
        targetSdk 36
        versionCode 4
        versionName '0.4-gps-status-reset'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
